### ISSUE TITLE
Forbidden use of library to load shader

### ISSUE THREAD

**Issue by pulgamecanica** [DimiOui/42-PCC-SCOP#1]
Hello there, I was exploring your repository and others, because I wanted to confirm that this is indeed (*not allowed*) by the subject. I wanted to see how others would be loading their shaders, so I guess we are supposed to actually recreate this function instead of using a library, no?

![image](https://github.com/DimiOui/42-PCC-SCOP/assets/28810331/00737a32-166e-4b1f-8169-8f2878fe4b18)

https://github.com/DimiOui/42-PCC-SCOP/blob/fb0ea45366b794ee8c03fed2fd69da00a7ce8278/VulkanTest/srcs/graphics_pipeline.cpp#L134

**Comment by jagged-teeth** [comment]
Hey Andre, thanks for your interest in the project I made and for bringing up your concerns !

As usual with 42 subjects, it's sometimes in a grey area. To clarify, the `createShaderModule` function is indeed a custom implementation I wrote to encapsulate the `vkCreateShaderModule` call. It takes the loaded data from `readFile` to create a Vulkan shader module using `vkCreateShaderModule` , which is a Vulkan API call, thus not third party.

The `readFile` function is an essential part of the shader loading, it is also custom and serves to read the SPIR-V shader files from the disk, which is then fed to createShaderModule.

I can confirm though, that you need to create custom functions to load the 3D objects and textures.

I didn't correct the project yet, but I don't see a real problem here. Would they really want me to write a custom function to *create* the shader ? The use of `vkCreateShaderModule` is unavoidable when working with Vulkan, as it is the standard way to create shader modules. This is not something that would typically be "recreated," as it is provided by the Vulkan SDK and is necessary for interacting with the Vulkan graphics pipeline.

**Comment by pulgamecanica** [comment]
> Hey Andre, thanks for your interest in the project I made and for bringing up your concerns !
> 
> As usual with 42 subjects, it's sometimes in a grey area. To clarify, the `createShaderModule` function is indeed a custom implementation I wrote to encapsulate the `vkCreateShaderModule` call. It takes the loaded data from `readFile` to create a Vulkan shader module using `vkCreateShaderModule` , which is a Vulkan API call, thus not third party.
> 
> The `readFile` function is an essential part of the shader loading, it is also custom and serves to read the SPIR-V shader files from the disk, which is then fed to createShaderModule.
> 
> I can confirm though, that you need to create custom functions to load the 3D objects and textures.
> 
> I didn't correct the project yet, but I don't see a real problem here. Would they really want me to write a custom function to *create* the shader ? The use of `vkCreateShaderModule` is unavoidable when working with Vulkan, as it is the standard way to create shader modules. This is not something that would typically be "recreated," as it is provided by the Vulkan SDK and is necessary for interacting with the Vulkan graphics pipeline.
> 

This is probably something that we can bring up to discussion, tbh if I were evaluating, I think I would not allow the use of the function. Mainly because the subject says that you can only use external libraries to handle the window and events explicitly and that you cannot use libraries to load objects and shaders (I always take mlx as a reference, so any function similar to an mlx call would be allowed) which for example, if you decided to use mlx you would need to recreate a shader "interpreter".

But also I see how this is problematic with Vulkan...

I will try to gather more info about this

**Comment by pulgamecanica** [comment]
After reading and trying to understand, I think my conclusion is:
The subject is wrong. It's impossible to allow the use of Vulkan and later on say that you cannot use any libraries to load the shaders... it's contradictory, also I believe that YES we can go with the underline saying that it is not a library, it's an API thus, loading with the API does not apply as it would with a "Library"
cheers

**Comment by jagged-teeth** [comment]
Let me say that it is clear that this project wasn't designed to be done with Vulkan.

Now that you're post common-core, you should be totally aware of recurring subject problems throughout the whole cursus (A lot of them are flawed, and it's in not a huge problem in my opinion, we're here to learn and this goal is achieved).

With regards to shader loading in Vulkan: If you wanted to simulate the process without the function you would literally have to write driver-level code to communicate with the GPU. I think this is far beyond the scope of this project. Do you really think this is the point here ?

I hope this clarifies the point. Wishing you the best of luck with your learning journey!
